---
version: "2.1"
services:
  after-download-carer:
    container_name: mangrana_java_after_download
    image: after-download-carer:latest
    build: .
    volumes:
      - ./config:/config
      - ./tokens:/tokens