---
version: "2.1"
services:
  after-download-carer:
    container_name: mangrana_java_after_download
    image: xeviff/after-download-carer:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./tokens:/tokens
      - /volume1/jobs/sonarr:/jobs/sonarr
      - /volume1/jobs/radarr:/jobs/radarr