radarr_api_key: 1y2u2u3u4ui4o5o5hi
radarr_api_host: https://your-radarr.domain.is
sonarr_api_key: 1y2u2u3u4ui4o5o5hi
sonarr_api_host: https://your-sonarr.domain.is
downloads_team_drive_id: 23lk4kjh5k234thanks
movies_team_drive_id: 23oikj45lhello

