immortal_process: true
manage_failed_downloads: false
grabbed_file_identifier: -grab
radarr_api_key: 1y2u2u3u4ui4o5o5hi
radarr_api_host: https://your-radarr.domain.is
sonarr_api_key: 1y2u2u3u4ui4o5o5hi
sonarr_api_host: https://your-sonarr.domain.is
downloads_team_drive_id: 23lk4kjh5k234thanks
movies_team_drive_id: 23oikj45lhello
series_team_drive_id: 23oikj45lhello
plex_token: q1Ej435345E2zJj
plex_url: https://your-plex.domain.is
plex_section_refresh_uri: /library/sections/{section_id}/refresh
google_retry_interval: 30
sonarr_retry_interval: 5
sonarr_paths_starter: /tv
plex_paths_starter: /mnt/mangrana_series